
install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'uuid', 'digest'), repos="https://cloud.r-project.org")
install.packages('IRkernel', repos="https://cloud.r-project.org")
IRkernel::installspec()
install.packages(c("rvest", "xml2", "dplyr", "stringr", "readr", "remotes", "devtools"))
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.15")
BiocManager::install(c("Spectra", "MsCoreUtils"))
BiocManager::install("CAMERA")
remotes::install_github("rformassspectrometry/MsBackendHmdb")
remotes::install_github("rformassspectrometry/MsBackendMsp")
remotes::install_github("rformassspectrometry/MsBackendMgf")
Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
install.packages("V8", repos="https://cloud.r-project.org")
devtools::install_github("End-to-end-provenance/provSummarizeR")
devtools::install_github("End-to-end-provenance/rdt")
#devtools::install_github("mmondelli/rdt2repr")