install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'), repos="https://cloud.r-project.org")
install.packages('IRkernel', repos="https://cloud.r-project.org")
IRkernel::installspec()
remotes::install_github("rformassspectrometry/MsBackendHmdb")
remotes::install_github("rformassspectrometry/MsBackendMsp")
Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
install.packages("V8", repos="https://cloud.r-project.org")
devtools::install_github("End-to-end-provenance/provSummarizeR")
devtools::install_github("End-to-end-provenance/rdt")
#devtools::install_github("mmondelli/rdt2repr")

